name: Satel-webapp-QA-deployment
description: Deploys webapp to QA VM/environment
inputs:
  app-name:
    description: Name of the webapp
    required: true
  satel-docker-user:
    description: Username for satel docker registry
    required: true
  satel-docker-pass:
    description: Password for satel docker registry 
    required: true  
  satel-registry:
    description: Satel registry address  
    required: true  
  clean-branch-name:  
    description: Clean branch name
    required: true  
  work-dir:
    description: work directory
    required: false
  registry_type:
    description: Type of registry
    required: false

runs:
  using: "composite"
  steps:
    - name: Deploy to QA VM
      env: 
        APP_NAME: ${{ inputs.app-name }}
        DOCKER_USER: ${{ inputs.satel-docker-user }}
        DOCKER_PASS: ${{ inputs.satel-docker-pass }}
        REGISTRY: ${{ inputs.satel-registry }}
        CLEAN_BRANCH_NAME: ${{ inputs.clean-branch-name }} 
        WORK_DIR: ${{ inputs.work-dir }}
        REGISTRY_TYPE: ${{ inputs.registry_type }}
      run: ${{ github.action_path }}/DeployToQA.sh  
      shell: bash
