name: Satel-webapp-QA-deployment
description: Deploys webapp to QA VM/environment
inputs:
  app-name:
    description: Name of the webapp
    required: true
  satel-docker-user:
    description: Username for satel docker registry
    required: false
  satel-docker-pass:
    description: Password for satel docker registry 
    required: false  
  satel-registry:
    description: Satel registry address  
    required: false 
  clean-branch-name:  
    description: Clean branch name
    required: true  
  work-dir:
    description: Work directory
    required: false
  registry-type:
    description: Type of registry
    required: false
  db_username:
    required: false
    type: string
  db_password:
    required: false
    type: string    
    

runs:
  using: "composite"
  steps:
    - name: Print envs
      run: | 
        echo MONGO_INITDB_ROOT_USERNAME: ${{ inputs.db_username }} ${{ env.MONGO_INITDB_ROOT_USERNAME }}
        echo MONGO_INITDB_ROOT_PASSWORD: ${{ inputs.db_password }} ${{ env.MONGO_INITDB_ROOT_PASSWORD }}
      shell: bash  
        
    - name: Deploy to QA VM
      env: 
        APP_NAME: ${{ inputs.app-name }}
        DOCKER_USER: ${{ inputs.satel-docker-user }}
        DOCKER_PASS: ${{ inputs.satel-docker-pass }}
        REGISTRY: ${{ inputs.satel-registry }}
        CLEAN_BRANCH_NAME: ${{ inputs.clean-branch-name }} 
        WORK_DIR: ${{ inputs.work-dir }}
        REGISTRY_TYPE: ${{ inputs.registry-type }}
        MONGO_INITDB_ROOT_USERNAME: ${{ inputs.db_username }}  
        MONGO_INITDB_ROOT_PASSWORD: ${{ inputs.db_password }}
      run: ${{ github.action_path }}/DeployToQA.sh  
      shell: bash
